Update deploy-container-security.yaml

diff --git a/.github/workflows/deploy-container-security.yaml b/.github/workflows/deploy-container-security.yaml
--- a/.github/workflows/deploy-container-security.yaml
+++ b/.github/workflows/deploy-container-security.yaml
@@ -15,7 +15,7 @@ on:
         type: string
       group_id:
         description: 'Group ID'
-        required: true
+        required: false
         default: '00000000-0000-0000-0000-000000000001'
         type: string
       ruleset_name:
@@ -78,6 +78,11 @@ jobs:
       - name: Create policy
         id: create-policy
         run: |
-          output=$(python trendmicro/scripts/create_policy.py)
+          python trendmicro/scripts/create_policy.py
+          output=$(python trendmicro/scripts/check_policy.py)
           policy_id=$(echo "$output" | grep "policy_id=" | cut -d'=' -f2)
+          if [ -z "$policy_id" ]; then
+            echo "ERROR: Unable to fetch POLICY_ID"
+            exit 1
+          fi
           echo "policy_id=$policy_id" >> $GITHUB_OUTPUT
